### PR TITLE
Flick modification

### PR DESCRIPTION
**Pull request by sebv**
- made everything optional
- added missing param
- changed command name

### CODE REVIEW

**Comment by sebv** [comment]
ping @moizjv @jlipps

**Comment by jlipps** [comment]
i don't see 'swipe' as a parameter here: https://code.google.com/p/selenium/wiki/JsonWireProtocol#session/:sessionId/touch/flick

**Comment by sebv** [comment]
It's in ios code.

**Comment by jlipps** [comment]
this should reflect what gets sent according to the protocol. if we're doing something funky we need to handle that at a different level

**Comment by sebv** [comment]
but it doesn't get passed, so we just get rid of it?

**Comment by sebv** [comment]
code is here: https://github.com/appium/appium/blob/e6927c60e2264e32eade441dbfbf57f183310b43/lib/server/controller.js#L917

**Comment by jlipps** [comment]
looks like we added a param that's not in the spec. we shouldn't have done that. now i think we should simply not care about the swipe option. it doesn't work in ios anyway, and people should be using the gestures api anyway and not the old /touch/xxx commands. i don't want us to update this file with params that aren't actually in the spec

**Comment by sebv** [comment]
cool that'll make the code simpler.

**Comment by jlipps** [comment]
yeah. basically people used to be able to POST /flick with a {swipe: true} parameter, just to make sure we used the underlying apple 'swipe' command instead of the 'flick' command. let's just not support this case anymore.

**Comment by jlipps** [comment]
the clients all implement `swipe()` using the gestures API now anyway so no one should miss this

**Comment by sebv** [comment]
still need to fix the `optional` and command name.

**Comment by jlipps** [comment]
ok LGTM

**Pull request merged**
