### PR TITLE
allow broader schemes in setUrl than just http(s)

### PR DESCRIPTION
**Pull request by jlipps**
@imurchie fighting against MJSONWP here, please review

### CODE REVIEW

**Comment by Jonahss** [comment]
Could we use an npm module for this? Something with the common protocols included. Rather than an all-inclusive regex.

**Comment by jlipps** [comment]
@Jonahss protocols can be arbitrary strings

**Comment by imurchie** [comment]
LGTM

**Comment by jlipps** [comment]
published as 1.0.5

**Comment by Jonahss** [comment]
I meant. If we use something like `url.parse` we can verify that it's a
valid url. not just that it contains a colon and some slashes.
Also: not all protocols have slashes after the colon.

**Comment by jlipps** [comment]
ah good point. i didn't assume that android uris must be valid urls but i suppose they might be (not sure how broadly url.parse construes a url---no domain, for example?)

**Pull request merged**
