### PR TITLE
add scroll resource route.

### PR DESCRIPTION
**Pull request by rafael-chavez**
related to this pull https://github.com/appium/java-client/pull/386/

### CODE REVIEW

**Comment by imurchie** [comment]
When the protocol changes, this test will almost always break: https://github.com/appium/node-mobile-json-wire-protocol/blob/master/test/routes-specs.js#L41

Run the tests locally (`gulp once`) to make sure it works before pushing and opening a PR.

**Comment by jlipps** [comment]
@rafael-chavez where does this route come from? I'm not familiar with it in the spec

**Comment by imurchie** [comment]
I think it is a vendor-specific thing, to implement [this sort of thing](http://developer.android.com/training/gestures/scroll.html). If so, it ought to be behind the `appium` part of the protocol (so something like `/wd/hub/session/:sessionId/appium/element/:id/scroll`)

**Comment by rafael-chavez** [comment]
sorry your right @imurchie this is a vendor specific protocol route. I will change to be behind the appium vendor extension.

**Comment by jlipps** [comment]
Not just that, but just putting it behind the appium vendor extension doesn't mean we want to support it. Which driver currently implements (or will implement) this endpoint?

**Comment by rafael-chavez** [comment]
the facebook WebDriverAgent currently supports this endpoint., Well it supports the:
/wd/hub/session/:sessionId/uiaElement/:id/scroll 

therefore if i was to hide it behind the appium vendor protocol, then i would have to map it as appropriate in the appium-xcuitest-driver. 

I think we would want to support this right @jlipps ?

**Comment by rafael-chavez** [comment]
Would that be appropriate to put behind the appium vendor extension @jlipps ?

**Comment by jlipps** [comment]
I'm just wondering if the right thing to do is ask WDA to become more spec-compliant. Why can't we use https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidtouchscroll for example?

**Comment by rafael-chavez** [comment]
@jlipps it seems that scroll may be different, its scrolling based on coordinates as opposed to scrolling an element into view. However looks like that already exists and returns element location.

https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidelementidlocation_in_view

Ill close this out as it seems redundant since this already exists and its spec compliant.

**Comment by jlipps** [comment]
@rafael-chavez correct, it simply makes us pause to ensure that we haven't made an accidental change to the protocol

**Comment by rafael-chavez** [comment]
@jlipps i agree we should have the touch scroll added to WDA. But as far as scrolling with direction, would you be ok with hiding this behind the appium extension?

**Comment by jlipps** [comment]
I'm a little torn here. For years we've supported this by using `mobile: scroll` via execute script. I'm inclined to just keep doing that and add logic that proxies to an actual endpoint in WDA if that's what they chose (but still, they should update it so that it's hidden behind a vendor extension)

**Comment by rafael-chavez** [comment]
Your suggesting adding some translation in the appium-xcuitest-driver that calls the correct endpoint when executeScript is called? 

Yes the issue is that the endpoint currently set in WDA has 'uiaElement' in the endpoint. I will open an issue to see if they are willing to fix it.

**Comment by jlipps** [comment]
Yes, we currently have handling for `mobile: scroll`. I'm suggesting adding that handling to the appium-xcuitest-driver and proxying when we get in that handler. see https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/touch-actions.md#bugs-and-workarounds

**Comment by rafael-chavez** [comment]
Ok sounds good, ill look into this @jlipps.. Closing this out.

**Pull request closed without merging**
